version: '3.8'

services:
  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    ports:
      - "3306:3306"
    volumes:
      - mysqldb_data:/var/lib/mysql
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s

  backend:
    image: taeyoungkims/hackathon:latest
    container_name: backend
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    depends_on:
      mysqldb:
        condition: service_healthy

volumes:
  mysqldb_data:
  logs:
